services:
  envoy:
    # image: envoyproxy/envoy:v1.32-latest
    build:
      context: envoy
    container_name: envoy
    depends_on:
      vector:
        condition: service_started
      app:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
    environment:
      - DEBUG_LEVEL=info
      - USE_STATSD=true
      - SERVICE_NAME=app
      - SERVICE_PORT=80
      - LOG_PROCESSOR=vector
    networks:
      - envoynet
    ports:
      - "80:9000"
      - "19000:19000"
      - "19010:19010"
    volumes:
      - ./envoy/envoy_log2grpc.yaml:/config/envoy.yaml
      - ./logs:/logs  
  app:
    container_name: app
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 200M    
    image: fimal/perf-nginx:latest
    networks:
      - envoynet
    ports:
      - "9090:80"
  vector:
    container_name: vector
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
    # environment:
    #   VECTOR_LOG: DEBUG
    image: timberio/vector:0.44.0-debian
    networks:
      - envoynet
    ports:
      - "8125:8125/udp"
      - "50051:50051"
      - "50052:50052"
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      - ./logs:/logs 

  # k6:
  #   container_name: k6
  #   command: /tests/start_k6.sh
  #   depends_on:
  #     envoy:
  #       condition: service_started       
  #   entrypoint: /bin/sh     
  #   image: grafana/k6
  #   networks:
  #     - envoynet 
  #   volumes:
  #     - ./k6:/tests
networks:
  envoynet:
    driver: bridge
    name: test
